#ifndef Q4_CONTROL_CONFIG_H
#define Q4_CONTROL_CONFIG_H

/* Q4 static recovery test parameters.  These are intentionally separate
 * from the frozen Q3 configuration so Q4 tuning cannot change the contest
 * Q3 sequence. */
#define Q4_DISTURBANCE_MIN_ANGLE_DEG 12.0f
#define Q4_DISTURBANCE_MAX_ANGLE_DEG 18.0f
#define Q4_DISTURBANCE_DURATION_MS 300U
#define Q4_DISTURBANCE_VERIFY_TIMEOUT_MS 800U
#define Q4_RECOVERY_ACCEPT_MS 2000U
#define Q4_RECOVERY_TIMEOUT_MS 10000U
#define Q4_VISUAL_READY_AGE_MS 250U
#define Q4_RECOVERY_CONFIDENCE_MIN 10U
#define Q4_START_POSITION_TOLERANCE_CM 2.0f
#define Q4_READY_CONFIRM_MS 500U
#define Q4_RECOVERY_LEAD_TIME_S 0.25f
#define Q4_RECOVERY_LEAD_TIME_S_ERROR_NEG 0.30f
#define Q4_RECOVERY_MAX_ANGLE_DEG 25.0f
#define Q4_RECOVERY_BREAKAWAY_START_DEG 10.0f
#define Q4_RECOVERY_BREAKAWAY_STEP_DEG 4.0f
#define Q4_RECOVERY_DIRECT_BREAKAWAY_DEG 4.0f
#define Q4_RECOVERY_DIRECT_BEAM_LIMIT_DEG 1.0f
#define Q4_RECOVERY_KP_BEAM_DEG_PER_CM 0.20f
#define Q4_RECOVERY_KP_BEAM_DEG_PER_CM_ERROR_POS 0.23f
#define Q4_RECOVERY_KD_BEAM_DEG_PER_CM_S 0.20f
#define Q4_RECOVERY_KD_BEAM_DEG_PER_CM_S_ERROR_POS 0.20f
#define Q4_RECOVERY_BRAKE_KP_BEAM_DEG_PER_CM 0.12f
#define Q4_RECOVERY_BRAKE_KD_BEAM_DEG_PER_CM_S 0.12f
#define Q4_RECOVERY_BRAKE_KD_OUTWARD_BEAM_DEG_PER_CM_S 0.16f
#define Q4_RECOVERY_CRUISE_KD_OUTWARD_BEAM_DEG_PER_CM_S 0.20f
#define Q4_RECOVERY_HOLD_KP_BEAM_DEG_PER_CM 0.10f
#define Q4_RECOVERY_HOLD_KD_BEAM_DEG_PER_CM_S 0.12f
#define Q4_RECOVERY_BEAM_LIMIT_DEG 1.80f
#define Q4_RECOVERY_BEAM_LIMIT_DEG_ERROR_POS 2.20f
#define Q4_RECOVERY_BEAM_LIMIT_DEG_ERROR_NEG 2.00f
#define Q4_RECOVERY_BRAKE_BEAM_LIMIT_DEG 1.80f
#define Q4_RECOVERY_BRAKE_BEAM_LIMIT_DEG_ERROR_NEG 1.80f
#define Q4_RECOVERY_HOLD_BEAM_LIMIT_DEG 0.50f
#define Q4_RECOVERY_BRAKE_FALLBACK_CM 7.00f
#define Q4_RECOVERY_BRAKE_FALLBACK_CM_ERROR_NEG 5.00f
#define Q4_RECOVERY_START_DELAY_MS 0U
#define Q4_RECOVERY_BRAKE_MARGIN_CM 2.00f
#define Q4_RECOVERY_MID_DISTANCE_CM 5.00f
#define Q4_RECOVERY_MID_BEAM_LIMIT_DEG 1.60f
#define Q4_HOLD_POSITION_TOLERANCE_CM 1.0f
#define Q4_HOLD_SPEED_LIMIT_CM_S 3.0f
#define Q4_HOLD_CONFIRM_MS 300U
#define Q4_RECOVERY_COMMAND_PERIOD_MS 30U
#define Q4_BREAKAWAY_HOLD_MS 350U
#define Q4_HOLD_BEFORE_ZERO_MS 1000U
#define Q4_ZERO_RETURN_TIMEOUT_MS 5000U
#define Q4_ZERO_RETURN_TOLERANCE_DEG 0.5f
#define Q4_ZERO_NUDGE_DEG 10.0f
#define Q4_NEXT_RUN_GAP_MS 1000U

/* Bounded X42S profile used only for the initial disturbance command. */
#define Q4_ACCEL_RPM_S 200U
#define Q4_DECEL_RPM_S 200U
#define Q4_MAX_SPEED_RPM 13.0f
#define Q4_MAX_CURRENT_MA 600U

#endif
